# Generated by Django 5.1.2 on 2024-12-02 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auftrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vergabenummer', models.IntegerField(unique=True)),
                ('optionsnummer', models.IntegerField(unique=True)),
                ('massnahmenummer', models.IntegerField(unique=True)),
                ('startdatum', models.DateField()),
                ('enddatum', models.DateField()),
                ('max_klienten', models.IntegerField(default=0)),
                ('mindest_klienten', models.IntegerField(default=0)),
                ('aktuell_klienten', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Niederlassung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaleinsatzplanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VollzeitaequivalentStunden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wert', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Betreuungsschluessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('klienten_pro_betreuer', models.IntegerField()),
                ('auftrag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='betreuungsschluessel', to='PersonaleinsatzplanHaeH.auftrag')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PersonaleinsatzplanHaeH.position')),
            ],
        ),
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=255)),
                ('nachname', models.CharField(max_length=255)),
                ('qualifikation', models.CharField(max_length=255)),
                ('max_woechentliche_arbeitszeit', models.IntegerField()),
                ('personalnummer', models.IntegerField(unique=True)),
                ('geburtsdatum', models.DateField()),
                ('vertragsbeginn', models.DateField()),
                ('vertragsendeBefristet', models.DateField(blank=True, null=True)),
                ('unbefristet', models.BooleanField(default=False)),
                ('niederlassung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='PersonaleinsatzplanHaeH.niederlassung')),
            ],
        ),
        migrations.CreateModel(
            name='Personaleinsatzplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gueltigkeit_monat', models.IntegerField(choices=[(1, 'Januar'), (2, 'Februar'), (3, 'März'), (4, 'April'), (5, 'Mai'), (6, 'Juni'), (7, 'Juli'), (8, 'August'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Dezember')])),
                ('gueltigkeit_jahr', models.IntegerField()),
                ('kostentraeger', models.CharField(max_length=255)),
                ('ersteller', models.CharField(max_length=255)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('in_bearbeitung', 'in Bearbeitung'), ('gueltig', 'Gültig'), ('archiviert', 'Archiviert'), ('storniert', 'Storniert')], default='entwurf', max_length=20)),
                ('niederlassung', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personaleinsatzplaene', to='PersonaleinsatzplanHaeH.niederlassung')),
            ],
        ),
        migrations.AddField(
            model_name='auftrag',
            name='personaleinsatzplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auftraege', to='PersonaleinsatzplanHaeH.personaleinsatzplan'),
        ),
        migrations.CreateModel(
            name='MitarbeiterBetreuungsschluessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anteil_stunden_pro_woche', models.FloatField()),
                ('kommentar', models.TextField(blank=True, null=True)),
                ('freie_stunden', models.FloatField(default=0)),
                ('total_hours', models.FloatField(default=0)),
                ('auftrag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mitarbeiter_betreuungsschluessel', to='PersonaleinsatzplanHaeH.auftrag')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='betreuungsschluessel_zuweisungen', to='PersonaleinsatzplanHaeH.mitarbeiter')),
                ('schluessel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mitarbeiter_zuweisungen', to='PersonaleinsatzplanHaeH.betreuungsschluessel')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PersonaleinsatzplanHaeH.position')),
            ],
        ),
    ]
