# Generated by Django 5.1.2 on 2024-11-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonaleinsatzplanHaeH', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiterbetreuungsschluessel',
            name='eingesetzte_stunden_im_plan',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='mitarbeiterbetreuungsschluessel',
            name='freie_stunden_im_plan',
            field=models.FloatField(default=0, null=True),
        ),
    ]
