# Generated by Django 5.1.2 on 2024-11-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonaleinsatzplanHaeH', '0003_remove_mitarbeiterbetreuungsschluessel_eingesetzte_stunden_im_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiterbetreuungsschluessel',
            name='total_hours',
            field=models.FloatField(default=0),
        ),
    ]
