# Generated by Django 5.1.2 on 2024-11-30 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonaleinsatzplanHaeH', '0004_mitarbeiterbetreuungsschluessel_total_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitarbeiterbetreuungsschluessel',
            name='freie_stunden',
        ),
        migrations.RemoveField(
            model_name='mitarbeiterbetreuungsschluessel',
            name='total_hours',
        ),
    ]
