# Generated by Django 5.1.2 on 2024-11-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonaleinsatzplanHaeH', '0005_remove_mitarbeiterbetreuungsschluessel_freie_stunden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiterbetreuungsschluessel',
            name='freie_stunden',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mitarbeiterbetreuungsschluessel',
            name='total_hours',
            field=models.FloatField(default=0),
        ),
    ]
