# Generated by Django 5.1.2 on 2024-11-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PersonaleinsatzplanHaeH', '0006_mitarbeiterbetreuungsschluessel_freie_stunden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betreuungsschluessel',
            name='abgedeckte_VZA',
        ),
        migrations.RemoveField(
            model_name='betreuungsschluessel',
            name='benoetigte_VZA_aktuell',
        ),
        migrations.RemoveField(
            model_name='betreuungsschluessel',
            name='benoetigte_VZA_max',
        ),
        migrations.RemoveField(
            model_name='betreuungsschluessel',
            name='benoetigte_VZA_mindest',
        ),
        migrations.RemoveField(
            model_name='betreuungsschluessel',
            name='differenz_VZA_aktuell',
        ),
        migrations.RemoveField(
            model_name='betreuungsschluessel',
            name='differenz_VZA_max',
        ),
        migrations.RemoveField(
            model_name='betreuungsschluessel',
            name='differenz_VZA_mindest',
        ),
    ]
